### ISSUE TITLE
deepdanbootu module never finishes loading

### ISSUE THREAD

**Issue by Gman0909** [arenatemp/sd-tagging-helper#26] opened 2022-11-27 17:53 UTC
Even with the correct folder for Automatic1111's WebUI, which has deepdanbooru woeking, the interrogate button never activates, with a tooltip that remains in the "loading" state forever, making the app impossible to use effectively.

**Comment by arenasys** [comment] 2022-11-28 08:38
the webui recently overhauled the deepdanbooru code, so this repo has been updated to stay compatible. however if you still have an old version of the webui then it will no longer work

**Comment by AyoKeito** [comment] 2022-11-28 11:36
Unfortunately, it still doesn't work.
I've just cloned this repo from scratch and cloned a newest webui, launched it with --deepdanbooru and it still doesn't work.
Sometimes it hangs, sometimes it crashes. But never works :(

**Comment by arenasys** [comment] 2022-11-28 20:28
then there should be an error in crash.log

**Comment by AyoKeito** [comment] 2022-11-28 21:56
No crash.log, but a localappdata\CrashDumps 2,75GB minidump and Windows Event:
```
python3.10.exe : C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\python3.10.exe  
Exception code: 0xc0000005  
Fault offset: 0x0000000000095c92 
Faulting process id: 0x9b30
```

**Comment by arenasys** [comment] 2022-11-28 23:29
a segmentation fault. does the crash happen when loading or when trying to interrogate an image?

**Comment by AyoKeito** [comment] 2022-11-29 09:27
After clicking "interrogate" it either just hangs up indefinitely or crashes after 10 seconds.
It doesn't matter what picture i use (at least one picture tend to hang up instead of crashing tho) or if webui is running or not.
One other thing that might (?) be the culprit is i've had dreamooth extension installed previously which is installing different version of torch:
`pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116`
I'm not sure if that matters, just in case.

Anyway, that was the first thing i've tried to "fix" so i downloaded the whole separate webui instance just in case. deepdanbooru is working in both webuis.

**Comment by neojam** [comment] 2022-11-29 13:50
"After clicking "interrogate" it either just hangs up indefinitely"

Yep I have same problem. Since its hanging, there is nothing in the log and I have to kill the process.
The problems started to occur right after the fix (https://github.com/arenatemp/sd-tagging-helper/commit/9aed12a1349bdfd3db81bc707c19c7b2b15c42e2) for https://github.com/arenatemp/sd-tagging-helper/issues/24  issue was applied.

**Comment by arenasys** [comment] 2022-11-30 14:04
should be fixed by 97a0a86763d5845e8b065209c99f842e65ba8b7b. it seems pytorch will segfault if the model isnt loaded in the main thread. as a consequence it will take longer to launch the application now

**Comment by arenasys** [comment] 2022-11-30 14:06
also this only affected my windows machine so it took a while to reproduce. i will leave this issue open incase theres some other torch configuration that has problems.

**Comment by arenasys** [comment] 2022-11-30 23:02
after some testing i found that the fault happens when torch isnt imported on the main thread. so i can move model loading back into the background so the GUI doesnt freeze.

**Comment by neojam** [comment] 2022-12-01 16:36
Works now, thanks

**Closed as completed** 2022-12-02 23:41 UTC
